### ISSUE TITLE
Support for MERGE?

### ISSUE THREAD

**Issue by lwalker-kforce** [roadrunnerlenny/etlbox#13]

**Comment by lwalker-kforce** [comment]
The docs indicate that DBDestination does inserts. Is there a way to do a MERGE instead?

**Comment by lwalker-kforce** [comment]
The docs indicate that DBDestination does inserts. Is there a way to do a MERGE instead?

**Comment by roadrunnerlenny** [comment]
HI, 
thanks for your interest in ETLBox! 
This is a very good question. The option to directly merge (or "Upsert") data from an in-memory dataflow into a database is something which would be very nice to have. 

Unfortunately, the short answer to your question is: No, there is no support for a merge or upsert implemented.
The reason for this is that the DB Destination does a Bulk insert into the database. If we encounter big amount of data, a bulk insert is the only performant way to insert data into the DB. The underlying ADO.NET does not support a merge directly on the database.

I remember this is exactly the same problem as in SSIS, an ETL tool from Microsoft. There was also no possibility to MERGE or UPSERT data, basically for the same reason.

You have two options here:
1. Create a "staging" table where you enter the newly loaded data. After you finished the load, use the `SqlTask` to execute a MERGE statement between your staging and your destination table.

2. Use the `Lookup` component to have all the data from your destination in your data flow available. Then, based on this data, do the modifications to your existing data. Truncate the destination table and insert the new modified data into table. (https://etlbox.net/api/ALE.ETLBox.DataFlow.Lookup-3.html) 

Does that answer your question?

**Comment by lwalker-kforce** [comment]
Yes, it provides the answer I expected. My MERGE data sets are small although there are a lot of sets so I am attempting to accomplish this with some variation of `ExecuteNonQuery`. 
_Note the below is incomplete at the moment. I am trying to figure out if I need to reset the `CurrentDbConnection` or if there is a way to do so in the `CustomDestination` like with the `DBDestination`. I'm not even sure at the moment if `CustomDestination` is appropriate._

Any pointers would be helpful.

``` Csharp
var dest = new CustomDestination<List<PlacementFamily>>(families =>
            {
                var insertBuilder = new StringBuilder();
                foreach (var family in families)
                {
                    //rows.Add(family);
                    insertBuilder.Append($@"insert into @tRelatedPlacements(ppid, poid, pcid, rpid, roid, rcid) 
values({family.PPID}, {family.POID}, {family.PCID}, {family.RPID}, {family.ROID}, {family.RCID});");
                }
                var sql = $@"declare @tRelatedPlacements table (ppid int, poid int, pcid int, rpid int, roid int, rcid int)
{insertBuilder.ToString()}
merge into dbo.PlacementFamilies as T
using @tRelatedPlacements as S
on (T.ppid=S.ppid and T.rpid=S.rpid)
when not matched then
insert(ppid, poid, pcid, rpid, roid, rcid) values(S.ppid, S.poid, S.pcid, S.rpid, S.roid, S.rcid);";

                SqlTask.ExecuteNonQuery("", sql);

            });
```

**Comment by roadrunnerlenny** [comment]
Hi, 
I just saw your code and think you came up with a very good solution. The CustomDestination is actually a good approach to solve this problem - I didn't think of that before. 

I see that you are using a List a type for the custom destination. Actually, if you don't use a list, but only the object type `Placement family`in your destination, it would make more sense to me. The function in the constructor of the `CustomDestination` is called for every record that the CustomDestination retrieves. So your source should be something like 
`CSVSource<PlacementFamily> source = new CSVSource<PlacementFamily>`
and your Destination then 
```C#
CustomDestination<PlacementFamily> dest = new CustomDestination<PlacementFamily>(
  row => {
       sql = "... MERGE ... {family.PPID}, {family.POID} "
      SqlTask.ExecuteNonQuery("", sql);
}
```
You can leave out the foreach loop then.

This would execute the merge for every record. If you have only small datasets, this could work, but you will definitively get performance issues with a higher amounts of records. (Same with your approach above, as you have an INSERT into the table variable for each record )

The `ControlFlow.CurrentDBConnection` is always used if no other connection is specified. You can always provide the connection directly if you an instance of the object, e.g.
`new SqlTask("",sql) { ConnectionManager = .. } . ExecuteNonQuery()`
Perhaps this article helps you: https://etlbox.net/articles/example_different_dbs.html

**Comment by lwalker-kforce** [comment]
Thanks for the tip on the `ConnectionManager`. 

It might help to know that I have a `RowTransformation<Placement, List<PlacementFamily>>` in front of the `CustomDestination`. The transform essentially executes a SPROC on the `Placement` and returns 0:n rows of `PlacementFamily`. That is why my input on the `CustomDestination` is a `List<PlacementFamily>`. Let me know if I am approaching that incorrectly but I thought that is how it should work.

**Comment by roadrunnerlenny** [comment]
Hey again,

if you call a Stored Procedure within a `RowTransformation` you should be aware that the Stored Procedure is called for every record that goes through the RowTransformation. This could slow down your data flow, but if you deal with small sets of data this should be fine.

If you want to process a whole set of data and pass it to a Stored Procedure (mostly because of performance reasons), you could have a look at the `BlockTransformation`. It basically "stops" the dataflow until all data are loaded into the Transformation, and then give you access to a  List that contains all records.The downside here is that if you want to transform the object into another type, you have to connect it to another row transformation. I am currently working on BlockTransformation that allow to have that build-in.

Here is an example:
```C#
BlockTransformation<Placement> bt = new BlockTransformation( 
  allPlacements =>   { 
      List<Placement> result = new List<Placement>() ;
      result.AddRange(allPlacements);
     return result;
});
```

**Comment by roadrunnerlenny** [comment]
Hi again,

I just was able to modify the BlockTransformation that it allow not only to return the same object type, but also allows to return a list with different output type. It would look like this:
```
BlockTransformation<Placement, PlacementFamily> bt = new BlockTransformation( 
  allPlacements =>   { 
      List<PlacementFamily> result = new List<PlacementFamily>() ;
      result.AddRange(ConvertFunctionHere(allPlacements));
     return result;
});
```
I would add some tests and release a new version pretty soon. (1.2.4)

**Comment by roadrunnerlenny** [comment]
Just uploaded version 1.3.0 which contains the extended BlockTransformation.

**Comment by lwalker-kforce** [comment]
I'll give it a look/try. My transform is accepting a single row, doing a lookup to get multiple rows back. (e.g. for every placement id of x, find all related placements to it where linktoplacement = x. So, the SPROC would take a single ID and provide multiple records as a response. Will the BlockTransform still be approprate?

**Comment by roadrunnerlenny** [comment]
Currently, when you call a Stored Procedure within a row transformation, you will call it for every records which goes through the Row Transformation. So, when you receive 10 rows of Placement, you will call the SPROC 10 times, each time with a new ID. (As a result you would get 10 Lists of PlacementFamily)
This works fine for a small amount of data, e.g for 1000 or even perhaps 10.000 rows. But the more records you feed into the dataflow, the slower the whole thing will get. For 100.000 records the SPROC will be called 100.000 times, each time one ID of the `Placement` would be passed to the SPROC - and things can become slow.
Sql Server (or any Sql databases) works bests with set operations and complete sets of data. So if you want to have this setup performant for big amount of data, this is where the `BlockTransformation` would come in. 
In the BlockTransformation you would get a `List<Placement>`, containg all Placement objects of the flow and therefore all ID. You could then pass *all* IDs to the Stored Procedure (instead of only one per row). The result would be a `List<PlacementFamily>`, which would contain all PlacementFamily objects for all Placements. 
This way you would have the same result set, but you would only call the SPROC once. But it would mean modifications to your code and your SPROC.
Again, this is only necesarry if your dataflow exceed a particular amount of data or becomes to slow.

**Comment by roadrunnerlenny** [comment]
I have good news.
Starting with version 1.3.1, I added a DBMerge dataflow component. 
Here is an example how to use it:

1. Your data object needs to implement the new interface `IMergable`:

https://github.com/roadrunnerlenny/etlbox/blob/af8d72e993408dc229f3a8012077718365fd780c/ETLBoxTest/src/DataFlow/TestDataFlowDBMerge.cs#L29-L49

2. You need to have some source and destination tables, in this example like this:
https://github.com/roadrunnerlenny/etlbox/blob/af8d72e993408dc229f3a8012077718365fd780c/ETLBoxTest/src/DataFlow/TestDataFlowDBMerge.cs#L114-L133

3. Now you can use the `DBMerge`
https://github.com/roadrunnerlenny/etlbox/blob/af8d72e993408dc229f3a8012077718365fd780c/ETLBoxTest/src/DataFlow/TestDataFlowDBMerge.cs#L64-L78

Please not that the DBMerge does an update by deleting an reinserting the record.
