### ISSUE TITLE
How to get identities / ID of newly inserted records

### ISSUE THREAD

**Issue by weedkiller** [roadrunnerlenny/etlbox#15]
Hello, is there a `out` _mechanism_ to get the `ids `of what was inserted in the ETL inserts.

**Comment by roadrunnerlenny** [comment]
Hi,
thanks for your good question. Unfortunately, there is now special task in ETLBox that could help you with that. 
What you can do is:
Using a `SqlTask` that does the "INSERT INTO" and has an OUTPUT clause in there.
When you use an OUTPUT clause in an INSERT, the insert will return the newly inserted rows (and therefor also their IDs) 
When you use SqlTask.ExecuteScalar (for one row) or SqlTask.ExecuteReader (for multiple rows) you will the IDs.
Here an example on Stack Overflow, but instead of ADO.NET you can achieve the same with the `SqlTask`(as it is based on ADO.NET): 
https://stackoverflow.com/questions/18373461/execute-insert-command-and-return-inserted-id-in-sql

Here an example of the usage with `SqlTask`:
```
int id = SqlTask.ExecuteScalar("Test, @"INSERT INTO Table(Col1)  
OUTPUT INSERTED.ID VALUES (1)",);
```

You can use ExecuteReader if you want to insert multipe rows (you can have more than one value in an INSERT statement).

**Comment by weedkiller** [comment]
thanks for the response, can we wrap this inside ETLbox, with an out argument.
