### ISSUE TITLE
DBSource not working with SQL??

### ISSUE THREAD

**Issue by abdevny** [roadrunnerlenny/etlbox#17]
Hi, 

First time using ETLBox... I appear to be able to move the contents of a small source table to a dest table by specifying the table name in the source, however, when trying to move specific data using SQL - it never works and always reports back the following error:

System.Data.SqlClient.SqlException: 'Incorrect syntax near the keyword 'from'.'

Here is the Source: 
  DBSource source =   new DBSource(
                    new SqlConnectionManager(new ConnectionString(works_qa)), "select * from dbo.abSourceTest");

**Comment by roadrunnerlenny** [comment]
Hi,

thanks for using ETLBox. 
I looked into your issue, and you found a bug with the constructor of `DBSource`. Luckily, this is only a minor bug - the problem here is that I changed the constructor overload for `DBSouce<TOutput>` and forget to adjust the naming.

The constructor actually should look like this:
`public DBSource(IConnectionManager connectionManager, string tableName)`

but instead of tableName the variable name is sql which is confusing. It actually expects a tableName.
That's why you got an error message. 

I will change the naming of the variable in the next version.

So, if you want to pass a sql statement instead of a tablename, please use the following:

```
DBSource source = new DBSource() {
   ConnectionManager = new SqlConnectionManager(new ConnectionString(works_qa)), 
    Sql = "select * from dbo.abSourceTest"
};
```

There is also a test that shows the use of an sql statement:
https://github.com/roadrunnerlenny/etlbox/blob/e03fb8cc643cb07ccd88d6fd75aaa72ca027763b/ETLBoxTest/src/DataFlow/TestDataFlowDBSource.cs#L100-L118

I hope that answers your question?

**Comment by abdevny** [comment]
Thanks for the quick response.  We were able to get it working but with some pain.  It seems to work smoother when you want to do a complete table load from one db to another (without a class).  Once you select individual columns from your table in the sql, you have to define the class to contain the exact same columns or it throws out of bounds array errors.

Is there a way you can allow x # of cols selected in SQL and a prefetch function that would return back a class defined dynamically for the user?  

Something like:

var source = new DBSource()
            {
                Sql = "select col2,col3 from dbo.testTableSource"
            };

var myDynamicType = source.GetClassFromSql();


Another big thing is the fact that I can't use ETLBox with a winform app... which is HUGE.  Esp building some useful visual tools for moving data.  Any plans to go to Standard?  That way it'll work across the board..

Thanks again!

**Comment by roadrunnerlenny** [comment]
Hi, 

great that you were able to make things work.

if you use the non generic implementation like `DBSource` or `DBDestination`, the underlying code will basically use a string array as a type to wrap the data. When you write into a destination, it will use the string array to write into the table. You said you got an "out of bounds" exception. 
Do you still have the code available that created the exception? I would like to have a look at into this, perhaps it is a bug in ETLBox. I can think of 2 scenarios here: You either write into a table that contains less columns than you have in your dataflow, or the table has more columns. Could you describe your setup here?

Regarding your question, I probably need some clarification here.  If I understand you right, you don't want to define your class that holds the data beforehand, you would like to have the class created during runtime. 

So the method `source.GetClassFromSql()` should return the class dynamically for you. 
As C# is a typed language and normally expects all data types to be defined before compilation, this can be kind of tricky. So what would be the return type of `source.GetClassFromSql()` ? How should the class look like, or how would you access `var myDynamicType` later in the code? Currently, I don't really have an idea how to implement this.

Regarding the Winform app: Issue #12 asked the same question. 
Unfortunately, the current version of ETLBox only support .NET Core. As a workaround, I would recommend to use the `Process` object to start a .net core console application that holds the dataflow. 
But for future versions, I would love to have ETLBox running with .NET Standard. I already tried to make it work, but I am struggling with this task. I could need some help here - perhaps you would to participate?

**Comment by roadrunnerlenny** [comment]
I just committed a fix - if you specify a sql statement and use the non-generic `DBSource` implementation, there was an error when reading the data from the source. This fix will be part of the next version (>1.3.3), which I probably will release in the next couple of days.

**Comment by jhurdlow** [comment]
You need to update the documention here: https://etlbox.net/index.html as it shows (under the 'Data flow tasks - examples' section) to use:
``` csharp
DBSource<MySimpleRow> source = new DBSource<MySimpleRow>("select * from dbo.Source");
```
which is not valid and throws the 'Incorrect syntax near the keyword 'from'.' error.
I struggled with this error for quite a while before finding this issue here on GitHub.

**Comment by roadrunnerlenny** [comment]
Hi, 
Thanks for pointing out the error in the documentation. I will fix this in the next couple of days.
