### ISSUE TITLE
 Using platform-specific SQL

### ISSUE THREAD

**Issue by sendreams** [roadrunnerlenny/etlbox#26]
<img width="636" alt="2019-09-06_16-43-09" src="https://user-images.githubusercontent.com/4160051/64414398-da3bd600-d0c5-11e9-8e59-9d0cb9b3b3d9.png">
going to the `DropTableTask` class, find the sql using sql-server syntax：
`      public string Sql
        {
            get
            {
                return
    $@"
IF OBJECT_ID('{TableName}', 'U') IS NOT NULL
  DROP TABLE {TableName} 
";
            }
        }`

the property here should use a  primitive sqlstring.

**Comment by sendreams** [comment]
<img width="532" alt="2019-09-06_17-27-23" src="https://user-images.githubusercontent.com/4160051/64417446-a6fc4580-d0cb-11e9-95ff-7fe3ebd36e4a.png">

**Comment by anlennar** [comment]
Hi, 
thanks for reporting the bug. 
I will have a look into this.
I am currently refactoring my tests, so that all tasks will be tested for all supported connection managers. There are probably some other bugs with RowCount etc. which have some Sql Server specific sql in it. 
It will be fixed in the next version then, which will hopefully come out in the next 2 - 4 weeks.

**Comment by sendreams** [comment]
i think should be add a new interface to provider platform-specific sql string.  the sql hard code in task will be lead to many problems. 
then please add mysql and oracle support. thanks

**Comment by roadrunnerlenny** [comment]
I will work on a MySQL implementation that will fully support all tasks (ControlFlow, Dataflow) and use platform specific sql. Currently it is working for SQL Server and SQLite, I will let you know when I added MySQL.

**Comment by roadrunnerlenny** [comment]
Hi, just a quick update on this:
I just released version 1.6.0, which does now fully support SqlServer, SQLite, MySql and Postgres.
