### ISSUE TITLE
Does ETLBox support Oracle?

### ISSUE THREAD

**Issue by FelipeBleson** [roadrunnerlenny/etlbox#27]
Good afternoon,
I created new project using etlbox, but in the connection with oracle its happening the bug with the source code described below:

ControlFlow.CurrentDbConnection = new AccessOdbcConnectionManager(@"Driver={Microsoft ODBC for Oracle};Server=(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=111.000.000.000)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=teste))); User Id=user; Password=password;Connection Timeout=60;");
SqlTask.ExecuteReader("Read all data from table1", "select * from dual", col1 => Console.WriteLine(col1.ToString() + ","), col2 => Console.WriteLine(col2.ToString()));
CreateWebHostBuilder(args).Build().Run();

Bug's image :

![image](https://user-images.githubusercontent.com/36280917/66079088-c440fa00-e539-11e9-9fd0-feba1a04a6b2.png)

can you help me to figure out what i'm missing?

Thanks in advance!!

**Comment by roadrunnerlenny** [comment]
Hi Felipe,

thanks for using ETLBox. Actually, your are trying to connect to an Oracle Database which ETLBox in the current version (1.5.0) does not support. Currently, Sql Server and SQLite is supported, and the next version (probably 1.6.0) will add support for MySql and Postgres. I hope I can do a release of the next version in the next couple of days. After that, I will have a look at supporting Oracle. I can keep you updated of the progress if you want.

**Comment by roadrunnerlenny** [comment]
Hi, just a quick update on this:
I just released version 1.6.0, which does now fully support SqlServer, SQLite, MySql and Postgres.

I had a look at Oracle,  and implemented a basic connection manager. (Added to branch https://github.com/roadrunnerlenny/etlbox/tree/Oracle_Support). Also, I had a look what would be needed in order to fully support Oracle. 
Unfortunately, to have a full support implemented, it looks like a lot of additions/changes would be needed to the current codebase. Oracle does behave different compared to Postgres or MySql. I will put it on my TODO list, but it probably it will take some time until I have the chance to implement it. 

By the way, I am still looking for volunteers - if you want, you can help me implementing the Oracle support.

**Comment by karg-betacode** [comment]
Hi, we might want to use this for our client too. They are using oracle.
I can try to help with getting the Oracle support, if this answers your request for volunteer part.

**Comment by roadrunnerlenny** [comment]
Hi karg-betacode,

that actually would be great! 

Here is how I far I got with Oracle:

I got an Oracle Docker image up and running - serving an Oracle Database.

The ADO.NET connector seems to work fine, on first glance it worked as expected.
As usual there is missing a good Bulk insert functionality. Any suggestions here? 

In order to have all developments proper tests, ETLBox comes with a lot of tests. All tests are basically expecting an "empty" database. E.g., for SqlServer you install the database server (called instance), and within an instance you can create and delete databases. So at the beginning of the tests I deleted this existing database and create a new one (using the CreateDatabaseTask).This works the same for Postgres and MySql (in MySql it's called Schema). But in oracle this is not working - there is only one Database (the one I did setup with Docker). But currently I don't want to recreate a whole container every time I run a test (I assume it just will take to long until my test is running). So I need some good way to clean up the existing database. Some articles are talking about deleting and creating users, but this seemed a little bit confusing to me at first glance.
Any advice here? 

Finally, I would need to have SQL code that gives me meta data about a table and it's definition (column names, types, primary key, identity or sequence if any, default values,...) Sorry if use the wrong terminology, most of the times I work with Sql Server.
So it would be helpful if you could assist me here? For MySql it looks like this: https://github.com/roadrunnerlenny/etlbox/blob/4faf8379f324270b13c75dbe76a497744439b99b/ETLBox/src/Definitions/Database/TableDefinition.cs#L161-L208

This are the main issues I currently have. Any help would be highly appreciated!

**Comment by karg-betacode** [comment]
Thanks for the details. Not an oracle developer but i see what i can do.

**Comment by drocdotCode** [comment]
@karg-betacode are you working on this now?

**Comment by burnbay** [comment]
Hi!

Did you take a look at the OracleBulkCopy class: https://docs.oracle.com/cd/E11882_01/win.112/e23174/OracleBulkCopyClass.htm#ODPNT7446

It would also be nice to extend the IConnectionManager interface with a method like BulkInsert(IDataReader reader, string tableName) to support data streaming.

**Comment by roadrunnerlenny** [comment]
Hi @burnbay,

thanks for pointing out the OracleBulkCopy. Wasn't aware of that, that actually looks like exact the kind of object needed to implement the bulk insert in the `OracleConnectionManager`.

Still this would leave the questions open about a good setup to create the Test environment and the question how to retrieve the meta data information. Any ideas here?

The `IConnectionManager` already implements the `BulkInsert(IDataReader reader, string tableName)`method - it is implemented by DBConnection, and because all ConnectionManager derive from this base class they actually implement that Interface. So I'm not quite sure what your question here is?

**Comment by burnbay** [comment]
My mistake. Didn't see the implementation of IDataReader.

I'm not at all an Oracle expert, but maybe this is something that could be used: 
- http://www.dba-oracle.com/oracle_tips_dbms_metadata.htm
- https://docs.oracle.com/database/121/ARPLS/d_metada.htm#ARPLS026

**Comment by roadrunnerlenny** [comment]
@burnbay: thanks for looking up information. 
Ok, I think I could dig my way through Oracle Sql specificas to retrieve schema information. 

The remaining issue - which actually is the most important one, because otherwise I won't be able to setup my test environment - is how to remove all objects from an existing database, so that I have a "clean" test environment before my test runs. Setting up a new docker container is not an option for me, because that would speed things down to much to work with. 
In other databases like SqlServer I just drop the database, and create a new one - but this doesn't work with Oracle. 

Any ideas here?

**Comment by flopgiggle** [comment]
Thanks for providing such an excellent etl tool。Is there any progress in this matter? Our team has always used oracle. At present, I want to replace ssis. It seems that only this framework is suitable. We will be very happy if we can support it.

**Comment by roadrunnerlenny** [comment]
Hi @FelipeBleson ,

thanks for the feedback. Support for Oracle (and also other databases) is still on my roadmap. 
Currently my plan is to have the connection managers separated into their own packages (e.g. ETLBox.SqlServer, ETLBox.MySql etc.) so that references to other packages are reduced to the ones that you are actually using. After this, I plan to work on an implementation of a connection manager for Oracle. 
 This project is open source for a while now, and I am still the main contributor for > 99 % of the code changes etc. So in order to push this forward, I would like to spend more time on improving this project. But to  do, it could be that this Oracle connection manager (which would not affect the current code) would not be open source and comes with a price tag for commercial use. Would that be an option for you?

**Comment by roadrunnerlenny** [comment]
Hi @FelipeBleson ,

I was able to implement full Oracle support in ETLBox. 
The new version 2.0.1 (https://www.nuget.org/packages/ETLBox/) now supports oracle as connection type - and works with the Oracle connection manager: https://www.nuget.org/packages/ETLBox.Oracle/

Please not that the connection managers are now in separate packages and are closed source with a different license model. (https://etlbox.net/articles/pricing/pricing.html)

But of course the existing nuget package can be used for either personal use or for development purposes, so you can try it out and see if ETLBox and the new connection manager suits your needs. 

Let me know if you have any issues using the new `OracleConnectionManager`.
