### ISSUE TITLE
ExecuteAsync does not return a Task

### ISSUE THREAD

**Issue by matt-lethargic** [roadrunnerlenny/etlbox#28]
`ExecuteAsync` on `CSVSource` does not return a `Task`, this is most strange and doesn't conform to the accepted practices of async all the way from the top to bottom of the stack. Also it calls `.Wait()` on `ReadAll()` so why not use `await` and return a `Task`? To compound this the `Execute` method directly calls `ExecuteAsync` so when a consumer thinks she is calling a synchronous method she's actually not... and could suffer deadlocks.

[Interesting article on blocking async/await](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html)

**Comment by roadrunnerlenny** [comment]
Hi matt-lethargic,
thanks for your interest in ETLBox and filing this bug report. You are right, the execute method definitly does not behave like other async methods in C# .
ETLBox classes and objects were designed to be as easy as possible to use. Especially for users who are not so deep into C# programming it still should be possible for them to use the library. Using the TPL library and the async / await keywords sometimes can be very hard to handle, even for experienced programmers. 
That's why I encapsulated the async pattern in a synchronous method call in the first place. You are right, there should be at least one method which does return the Task itself - e.g. the ExecuteAsync mehod. 
But there also needs to be some kind of method that can be called in a synchronous context. Any ideas how this could be offered to a user?

**Comment by roadrunnerlenny** [comment]
@matt-lethargic  Thanks for your input. I had a deeper look at the methods and the implementations and did some modifications here. Actually, I aligned all my sources and they are now using synchronous methods only. I kept the Execute- method on the sources, but it is just a reference to the `PostAll()` method. The `PostAll` ist the replacement for the `ExecuteAsync`, as it won't do any async stuff anymore (and actually never did before). The `PostAll` will synchronously post all records into the data flow pipe.
The `Wait()` method on the destination will wait until all records were received by the target. 

The method names `PostAll()` and `Wait()` are the same names as used in the underlying TPL.Dataflow library from Microsoft. Writing into the Buffer is done with the `Buffer.Post()` method, and on the Destination the `Wait()` methods is wrapping the `Wait()` on the completion of the target action.

**Comment by roadrunnerlenny** [comment]
Hi,
just a quick update on this: 

I just released version 1.6.2 (https://www.nuget.org/packages/ETLBox/1.6.2) which now has new methods to support parallelism:
All dataflow sources now support async Task ExecuteAsync().
All dataflow destinations now have asny Task Completion()

Calling the ExecuteAsync() will return a new Task. The Task is completed when all data from the source is posted into the dataflow.
Calling the Completion() method will also return a new Task. This task is completed when all data arrived at the destination.
