### ISSUE TITLE
Question: How does the sync work?

### ISSUE THREAD

**Issue by jonyeezs** [roadrunnerlenny/etlbox#31]
Hi @roadrunnerlenny not sure the best way to contact you to query on etlbox.

Wondering how well it does for syncing initial loaded data to target when there are new updated data in source.

Does it just do a complete update and needs to be a mapped unique key?
Or just having a source -> destination `RowTransformation` will manage all the syncing for me?

**Comment by bencassie** [comment]
Hi there,

Yes I am also wondering about the upsert functionality of DBDestination. 

Many thanks,

**Comment by roadrunnerlenny** [comment]
Hi Jonathan

Thank you for using ETLBox. Of course you are welcome to raise any questions, bugs or feature requests here on github. 

You questions basically aims how to keep a source and destination table "in sync". I can see two different scenarios here:
Scenario 1: The source table does not have any information about its changes. So no delta information is provided by the source. 
Scenario 2: The source table has information about its changes. This can be e.g. a timestamp indicating when the record was inserted or updated. One thing which is problematic here is how deletions are handled. There could be an extra flag saying that a record was deleted (including the deletion time). Or it could be that deletions are not transferred at all, either because they don't happen or for other reasons. 

So the question here would be what scenario you are aiming at? Does your source provide any delta information, or will you always need a full sync (or both, because deletions are not flagged and you want something like a "daily" delta load and a weekly full syc)?

To tackle the sync problem with ETLBox, you can have a look at the `DBMerge` component. Unfortunately,  I hadn't had the time yet to write an article about this (it is still planned). In the meanwhile, you can have a look at the Tests to understand how it works:
https://github.com/roadrunnerlenny/etlbox/blob/dev/ETLBox/src/Toolbox/DataFlow/DBMerge.cs

The `DBMerge` basically is a destination table in your dataflow. It will wait for all data from the flow to arrive, and the either insert, update or delete the data in the detstination table. Deletion is optional (by default turned on) , and can be disabled with the property `DisableDeletion` set to true. The `DBMerge` was designed for scenario 1, but should also work for scenario 2. 

The idea to implement a sync between two tables would that you have a `DBSource` pointing to your source table. You can use either the tablename (this would be if you want a full sync) or a sql query (which gives you only the delta records). The source is then connected to the `DBMerge`, and data from the source will then be inserted, updated or deleted in the destination. The DBMerge has a property `DeltaTable` which contains additionally information what records where updated, inserted or deleted (also this information can be used as a source for further processing in the data flow, simple by connecting the `DBMerge` to a transformation or another Destination).
Please note that if you connect the `DBMerge` to a source that provide you with delta information only, you need to disable the deletions - in that case, deletions need to be handled manually.

The `DBMerge` currently works best for scenario 1. For scenario 2, deletions are a little problematic, but it will help you with Inserts/updates (=Upserts).

 But of course there are other data flow components that can be used (and perhaps are easier to handle). Please have a look at the following issue: https://github.com/roadrunnerlenny/etlbox/issues/13.

Does that help you with your question? Any feedback is highly appreciated, as it will help me to further improve this tool.

**Comment by jonyeezs** [comment]
Thanks! That's good enough information for now
