### ISSUE TITLE
Is there transactions & rollback support?

### ISSUE THREAD

**Issue by AlexVPerl** [roadrunnerlenny/etlbox#56]
This is more of a question. I didn't seem to find anything in the API docs, but is there any transaction & rollback support? If not, any plan to of adding?

Thanks.

**Comment by roadrunnerlenny** [comment]
Hi @AlexVPerl ,

that is acutally a very good question. 
Absolutely right, there is no documentation about it, because I wasn't able to look deeper into this topic. Perhaps now is a good time to clarify this. 

Right now, most of the things happening in ETLBox rely on the corresponding connection manager class, which itself is a wrapper for ADO.NET connection. Whenever something happens on the database, a clone (if LeaveOpen is left unchanged) of this connection manager is used  to get a pooled connection from the ADO.NET connection pool.  RIght now, there is no code availabe to explicitly open and close a transaction. 

Of course it would be good to have a better build-in support for transactions. The question would be: how would you like to control the transaction in ETLBox? Can you think of a good use case?
Currently, I can see two places where a transaction can become important: One place would be the SqlTask, when you want to run more than on sql in one SqlTask or you want to run a SqlTask several times within a transation. The other place would be when inserting data using a DbSource - data is written into the destination in batches (and if one record fails, I assume the whole batch will be rolled back, but I haven't tested that now). Now it could that you want to rollback all data if any of the records fails? But I am not quite sure how this should look like in terms of code. 

Any ideas and feedback is welcome.

**Comment by roadrunnerlenny** [comment]
Hi @AlexVPerl,

did this answer your question?

**Comment by AlexVPerl** [comment]
Hi @roadrunnerlenny, sorry for the slow response.

I agree, SqlTask would be a good place, as well the DbSource / DbDestination scenario. 

Another place that I think would be very convenient to have is the SqlConnectionManager. I feel it would offer good flexibility as it would also cover both SqlTask & DbSource / DbDestination use cases since they rely on SqlConnectionManager. 

Transaction could be opened on SqlConnectionManager class similarly to LeaveOpen flag, and committed at the end. Code-wise it could be similar to how MS handles it in SqlConnection - [link](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.begintransaction?view=netframework-4.8). Perhaps for convenience: SqlConnectionManager can have methods BeginTransation() & CommitTransaction. A few overloads (4 I think) may be needed to handle combinations of TransactionName & IsolationLevel parameters. Internally it could be a wrapper for MS's SqlConnection transaction related methods.

I think it could be a good starting point. Of course I am not 100% familiar with entire scope of ETLBox's API so curious to hear what you think. 

Thanks.

**Comment by anlennar** [comment]
Hi  @AlexVPerl ,
just a quick update on this. Thanks to your input, I started to investigate how transaction handling could be integrated. I tried to integrate it into SqlTask & DbDestination, but turned out that it wasn't really working there becuase of the dependency to the ConnectionManager. 
So you mentioned to implement it on the ConnectionManager similar to the LeaveOpen flag, which was a very good idea - I was able to implement the BeginTransaction(), CommitTransaction & RollbackTransaction methods there. Right now I will try out the possibility of working with transaction names and writing some tests for it. 
I'll hopefully will finish it soon and  will keep you updated.

**Comment by rolfik** [comment]
You can also use implicit transactions with [TransactionScope](https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope?view=netstandard-2.0)s.

**Comment by rolfik** [comment]
> Hi @rolfik ,
> thanks for pointing this out! I wasn't aware of this. I just did some shallow research, at first glance it looks like this is something that is supported but for SqlServer, but not always fully implemented for other DBs (Postgres, MySql, SQLIte). Do you have any experience with this?

@roadrunnerlenny we use it in our production systems with MS SQL Servers.
With transaction scopes it is much easier to manage complex operations spanning over multiple methods, because a scope is not a transaction, but may begin a new transaction if it is not yet in progress or opt out of current transaction etc.
You basically do:

    using (var scope = CreateSomeScope())
    {
        DoSomeDbWorkEvenWithInnerScopesInside();
        scope.Commit();
    }  // if an exception is thrown before commit, scope disposing rollbacks the transaction

**Comment by AlexVPerl** [comment]
@roadrunnerlenny and @anlennar thank you for your continued support and updates to ETLBox. Will be trying out the newly added transaction support in the next few days :)
