### ISSUE TITLE
Column Count is 0 when SELECT *

### ISSUE THREAD

**Issue by REN-I-9jo9** [roadrunnerlenny/etlbox#57]
Hi,I've found a bug when using DbSource, as title.
Here's the code:
```
var sourceCon = new SqlConnectionManager(new SqlConnectionString("Data Source=.;Integrated Security=false;User = user; password = psw; Initial Catalog = mydb;"));
DbSource<object[]> source = new DbSource<object[]>(sourceCon)
{
    Sql = "select * from mytable"
};

RowTransformation<object[], object[]> trans = new RowTransformation<object[], object[]>(Row =>Row);

var destobjs = new List<object[]>();
var cdest = new CustomDestination<object[]>(
    data =>
    {
        destobjs.Add(data);
    }
);
source.LinkTo(trans);
trans.LinkTo(cdest);

source.Execute();
cdest.Wait();

destobjs.ForEach(obj=> {
    Console.WriteLine($"{obj.Length} {string.Join("",obj)}");
});
```
And the obj.Length will be 0.
But if my sql string changes to
```
Sql = "select colA,colB,colC from mytable"
```
It will works normally.
This problem occurs when sql query was like SELECT * ...

Thanks.

**Comment by roadrunnerlenny** [comment]
Hi @REN-I-9jo9 ,
thanks for reporting the bug. I will have a look into this and keep you udpated on the progress. Should be not to hard to fix. 

As a side note, I am surprised that you are using an array of object as a data type. So far, there are only tests that cover string array, regular "POCO" objects and ExpandoObject (Since 1.8.0, the "default" type for components is an `ExpandoObject`).
It would be great if you let me know how the other data flow worked with the object array.

**Comment by REN-I-9jo9** [comment]
Hi
Object array works nothing special, it correctly pass datas between each other.
By the way,when I try to use DataRow type, errors will occur.
If data flow can support DataRow type directlly, it will be great.

**Comment by roadrunnerlenny** [comment]
Hi @REN-I-9jo9 ,
I had a deeper look at the issue. Actually, I am not quite if I will be able to fix this at all. 
The reason is that the "*" does not give any clue about the column names used which could be parsed from ETLBox. So the next step would be to analyze the statement and check the involved tables - which is harder as it sounds, because it is not only the table after from but could be also the result of one or more join expression (including subselects).
If you would use a data row object, ETLBox would try to determine the column names from the property. But with an object array this is also not possible.

So I will think about it a little bit more, but right now I can't see how to solve this. 
But if you are interested in all columns of a particular table, you should use the TableName property of DbSource instead passing an Sql. Your code then looks like this:

```
DbSource<object[]> source = new DbSource<object[]>(sourceCon, "myTable");
//or
DbSource<object[]> source = new DbSource<object[]>(sourceCon)
{
    TableName = "mytable"
};
```

The will internally be translated into a "SELECT * FROM mytable", but now the tablename is known and the column names will be read using information schema or sys-tables.

**Comment by REN-I-9jo9** [comment]
My project needs using complex sql string,so I can't using TableName instead,but thanks anyway.
