### ISSUE TITLE
Question about synchronous execution within data flow.

### ISSUE THREAD

**Issue by xdororo** [roadrunnerlenny/etlbox#61]
**Describe the bug**
I would like to run the data flow step by step and avoid async run.

**Steps To Reproduce - here is my code**
```
//step1
DbSource< Entity1> source1 = new DbSource< Entity1>(ControlFlow.DefaultDbConnection, "conn"){Sql = $@"xxx"};
	RowTransformation< Entity1> trans1 = new RowTransformation< Entity1>(
	myrow =>
	{ 
	  // store data into a lookup datatable
	});
	source1.LinkTo(trans1);
    source1.Execute(); 
	
//step2	
DbSource< Entity2> source2 = new DbSource< Entity2>(ControlFlow.DefaultDbConnection, "conn"){Sql = $@"xxx"};
	RowTransformation< Entity2> trans2 = new RowTransformation< Entity2>(
	myrow =>
	{ 
	  // lookup to the datatable created at step1 and fill out fields in Entity2 (select, group by  and do aggregation)
	});
	source2.LinkTo(trans2);
	trans2.LinkTo(DestA);
    source2.Execute(); 
	DestA.Wait();
	
//step3	
DbSource< Entity3> source3 = new DbSource< Entity3>(ControlFlow.DefaultDbConnection, "conn"){Sql = $@"join from DestA"};
	RowTransformation< Entity3> trans3 = new RowTransformation< Entity3>(
	myrow =>
	{ 
	  // source will be another table to join step2 result. and insert to DestB
	});
	source3.LinkTo(trans3);
	trans3.LinkTo(DestB);
    source3.Execute(); 
	DestB.Wait();

```
**Actual behaviour**
step 3 run earlier than before step 2 completion.

**Expected behavior**
I don't want async run because step 2 will refer the complete result of step 1, and step 3 must process with the complete result of step 2. so, successor step cannot start before the predecessor step  completed.

**Comment by roadrunnerlenny** [comment]
Hi @xdororo ,
thanks for using ETLBox and posting this bug request. 
So if I understand you right, Step1 is supposed to load data into some kind of List or IEnumerable. 
The issue here is that Step 1 doesn't have a destination component. So the execute will block execution until all data is posted into the data flow, but then continue with step 2. This doesn't mean that the RowTransformation started processing yet. Transformations don't have a Wait()- method, so you need to connect your flow into some kind of Destination.
You could try to connect your RowTranformation `trans1` to a VoidDestination - this basically will throw away all data, as you don't them any more. Then you could call wait() on the VoidDestination before you continue with step2.
Could you try out if this already solves your issue?

Of course instead of use a RowTransformation to save your data, you can replace it with a MemoryDestination. This destination will store the incoming data in a Collection which you can access via the property data. (https://etlbox.net/articles/dataflow/dataflow_file_sources_destinations.html#memorydestination)

Other than that, if you want to do some Lookup stuff you could also use the LookupTransformation (https://etlbox.net/articles/dataflow/dataflow_transformations.html#lookuptransformation) 
This transformation will load data from a particular source into memory before executing the residing row transformation -   then you can use the data from the lookup source within the row transformation of the lookup. 
If you need help here, I can gladly assist you here.

**Comment by xdororo** [comment]
@roadrunnerlenny 
Thanks for your prompt answer. Sorry I didn't put it right,  actually I have a DbDestination at step2 (DestA). 
If I understand correctly, I need a DbDestination both at step 1 and step2, when I calling DbDestination.Wait(), I can execute the flow step by step, right?

**Comment by roadrunnerlenny** [comment]
Exactly, the flow at step1 doesn't have Destination. You only want to load data into memory, so actually it doesn't have to be a DbDestination - there are other destinations you can use.
If you want to keep the RowTransformation, then just connect your flow at step1 with a `VoidDestination`

```
//step1
DbSource< Entity1> source1 = new DbSource< Entity1>(ControlFlow.DefaultDbConnection, "conn"){Sql = $@"xxx"};
RowTransformation< Entity1> trans1 = new RowTransformation< Entity1>(
	myrow =>
	{ 
	  // store data into a lookup datatable
	});
VoidDestination voidDest = new VoidDestination();
source1.LinkTo(trans1);
trans1.LinkTo(voidDest);
source1.Execute(); 
voidDest.Wait();
```

This should already do it. 
A small improvement would be to use the memory destination instead, so you could even save the RowTransformation here.

```
//step1
DbSource< Entity1> source1 = new DbSource< Entity1>(ControlFlow.DefaultDbConnection, "conn"){Sql = $@"xxx"};
MemoryDestination< Entity1> memDest= new MemoryDestination< Entity1>(); 
source1.LinkTo(memDest);
source1.Execute(); 
memDest.Wait();

//Data is now accessable in step 2 via memDest.Data  
```

If you want to create your own list and overwrite the default collection used by the MemoryDestination (by default it is a BlockingCollection), you could do it like this:

```
//step1
DbSource< Entity1> source1 = new DbSource< Entity1>(ControlFlow.DefaultDbConnection, "conn"){Sql = $@"xxx"};
MemoryDestination< Entity1> memDest= new MemoryDestination< Entity1>(); 
List<Entity1> myList = new List<Entity1>();
memDest.Data = myList;
source1.LinkTo(memDest);
source1.Execute(); 
memDest.Wait();

//Data is now accessable in myList
```

Does that make sense? I haven't tested the code above, but it is supposed to work like this.

**Comment by xdororo** [comment]
Hi @roadrunnerlenny 

I've tested the code and it's running well now. I will try MemoryDestination and LookupTransformation as well. Thanks.

**Comment by roadrunnerlenny** [comment]
Good to hear! Let me know if you need any help.
