### ISSUE TITLE
How can I read and write batch by batch?

### ISSUE THREAD

**Issue by RapidsoftAIM** [roadrunnerlenny/etlbox#64]
Hello. I need read batch from DbSource (PostgresConnectionManager) and write it batch to DbDestination (SqlConnectionManager) and do it in loop.

Anything like this:
```
var source = new DbSource(sourceConnectionManager, sourceTableName);
var destination = new DbDestination(destConnectionManager, destinationTableName);
source.LinkTo(destination);

var maxExportedId = SqlTask.ExecuteScalar(destConnectionManager, $"Get maxId of {destinationTableName}", $"SELECT MAX(Id) as Id FROM {destinationTableName}");
var batchSize = 5;
destination.BatchSize = batchSize;
var batchNumber = 0;
var processedRowsCount  = 0;
do
{
	source.Sql = $"SELECT * FROM {sourceTableName} WHERE Id > {maxExportedId} ORDER BY Id ASC LIMIT {batchSize} OFFSET {batchNumber * batchSize} ROWS";
	source.Execute();
	destination.Wait();

	processedRowsCount = source.ProgressCount;	
	batchNumber++;
}
while(processedRowsCount > 0)
```

This code work for only first batch :(

Thanks in advance!!

**Comment by roadrunnerlenny** [comment]
Hi @RapidsoftAIM ,
thanks for using ETLBox. 
So I understand that you want to "page" through your source table in Postgres and transfer it into a table in SqlServer. 
The code above is not working as you expect because a dataflow pipeline can only executed once. 
If you want to execute a dataflow again, you need to (re)create, link and execute the whole flow again. In your code it would look like this:

```C#
var maxExportedId = SqlTask.ExecuteScalar(destConnectionManager, $"Get maxId of {destinationTableName}", $"SELECT MAX(Id) as Id FROM {destinationTableName}");
var batchSize = 5;

var batchNumber = 0;
var processedRowsCount  = 0;
do
{
        var source = new DbSource(sourceConnectionManager, sourceTableName);
        var destination = new DbDestination(destConnectionManager, destinationTableName);
        source.LinkTo(destination);
	source.Sql = $"SELECT * FROM {sourceTableName} WHERE Id > {maxExportedId} ORDER BY Id ASC LIMIT {batchSize} OFFSET {batchNumber * batchSize} ROWS";
        destination.BatchSize = batchSize;
	source.Execute();
	destination.Wait();

	processedRowsCount = source.ProgressCount;	
	batchNumber++;
}
while(processedRowsCount > 0)
```

But actually you are using ETLBox not as intended. The whole do-while loop and the paging of data is something you should completely avoid. ETLBox already has a build-in buffering mechanism that allows you to read data from the source while writing it into the destination. 
So you could rewrite your code like this:

```C#
var source = new DbSource(sourceConnectionManager, sourceTableName);
var destination = new DbDestination(destConnectionManager, destinationTableName);
destination.BatchSize = 1000;
source.LinkTo(destination);
source.Sql = $"SELECT * FROM {sourceTableName} ORDER BY Id ASC";
source.Execute();
destination.Wait();
```
You could vary the BatchSize to your needs (it could be 5 as well), but with lower values you will probably get also a bad performance here. You can stick to the default (which is 1000) or try it with 10.000 which could give you a better performance with Sql Server. 

Does that answer your question?

**Comment by RapidsoftAIM** [comment]
Yes.
Thanks for the quick and detailed answer.
