### ISSUE TITLE
How to do aggregation functions / Sum or Count or Avg

### ISSUE THREAD

**Issue by weedkiller** [roadrunnerlenny/etlbox#7]
Hi I need to perform a sum on import, how can I set that up with your lib?

thanks

**Comment by roadrunnerlenny** [comment]
Hey Weedkiller,

I assume you want to do the sum, count or avg in a dataflow. In a dataflow data is written into the destination while simultaneously it is read from the source. That means, if you want to do a sum, count or avg calculation, you need to have a component that "stops" the dataflow, wait until all data is loaded into memory, does the calculation and then continues writing the data into the following components. This can be achieved with a `BlockTransformation`. A BlockTransformation does load all data into a List and you can perform any function (e.g. Linq queries) on it. Here is an example for a count:

```C#
int totalCount = 0;
CSVSource<Poco> source = new CSVSource<Poco>("data.csv"); 
BlockTransformation<Poco> blockTrans = new BlockTransformation<Poco>(inputList => 
{ 
  totalCount = inputList.Count();
  return inputList;
}); 
  
var dest = new DBDestination<Poco>("dbo.Table"); 
    
 source.LinkTo(blockTrans); 
 blockTrans.LinkTo(dest); 
 source.Execute(); 
 dest.Wait(); 
```

As you can see, the `BlockTransformation` gives you access to a List of your DataType, and you could do a simple count on it.  

Does that help you?

**Comment by weedkiller** [comment]
Great, 👍 to clarify once I stop the dataflow - I would have write my summation or other function inside the `BlockTransformation` here you showed me count, I would do a sum correct?

- [ ] Another question, is there anyway using your lib, to create a strongly typed datatype / POCO object like CHO Etl[ (here on github on the fly)](https://github.com/Cinchoo/ChoETL/issues/25#issuecomment-447585168) as I load the CSV file. 🍰

**Comment by roadrunnerlenny** [comment]
Exactly, a sum would be calculated at the exact same place where I did the count(). (E.g., something Like `inputList.Select ( poco => poco.intValue ).Sum()`

Regarding your second question, I'm not quite sure what you want to archive. Basically, if you don't know the datatype of source data, I would recommend that you start treating your data as string array. That means you would just use the non-generic class `CSVSource` (which is equivalent to a `CSVSource<string[]>`. Then you can decide if you want to try to make an object type out of it (e.g. by use a `RowTransformation<string[], POCO>` or if you just want to directly insert your data in to Database (e.g. using the `DBDestination` which is the same as `DBDestination<string[]>`. Of course you could also put `BlockTransformation<string[]>` in between to calculate a sum, but at some point you must know which part of your input data does contain number that can be summed up.

**Comment by weedkiller** [comment]
Hi @roadrunnerlenny, Its only for the first read of a CSV file that we need to the data type. 

Summary: just for the first time: I use the CSV file to create a new `POCO` object on the fly with the col's as datatypes. I do this by scanning the first few rows (5 or 10 rows) and then figure out datatype (Cho ETL) gives me the data type, he has a nice function to get it with the snippet of code.

Using these datatypes, I create a `datatable` in Sql Server. 

After this, its pretty much load new csv files data into that table, and normal data operations.

Thanks

**Comment by roadrunnerlenny** [comment]
Hey Weedkiller,

here is a solution that could solve your problem just to read the first rows of a CSV. In a `CSVSource`, you can set up a Configuration that defines which records to read and which to skip.

```C#
            CSVSource firstRows = new CSVSource("src/DataFlowExamples/Issue7.csv");
            firstRows.Configuration.Delimiter = ";";
            firstRows.Configuration.ShouldSkipRecord = row =>
            {
                rowCounter++;
                if (rowCounter >= 2)
                    return false;
                else
                {
                    DetectTypeByRow(row);
                    return true;
                }
            };
```

But as the underlying tool to read CSV file is the [CSVHelper library](https://joshclose.github.io/CsvHelper/), I would recommend that you directly use this library just to scan the first rows of the CSV file.

That way you can define your object type. If you want to directly load data into a DataTable, you can use the `CustomDestination` instead of the `DBDestination`.

Please note that the `DBDestination` does accept a string array, but still would transform the data automatically into the format of the destination table. E.g. if your string array consists of 2 columns, one string that contains an integer value and one string that actually contains a float, and your destination table would accept INT and DECIMAL as DB datatypes, the transformation into the correct data type would implicitly happen when writing into the source. 

Back to the `CustomDestination`: this could help you here. You could have something like this: 

```C#
CustomDestination<string[]> dest = new CustomDestination<string[]>(
                row => AddToDataTable(row)
);
```

This way you could create a DataTable with the information you previously got from reading the first rows of the CSV file. 

This is probably not fully solving your problem, but perhaps one of the approaches can help you.

**Comment by roadrunnerlenny** [comment]
Hey Weedkiller, 
were you able to solve your problem?

**Comment by weedkiller** [comment]
thanks, it comes close! 🤗 

wish list: would be nice to see this natively in you lib, did you see the link i attached.
