### ISSUE TITLE
Unable to Insert Records into Oracle

### ISSUE THREAD

**Issue by BabuBahir** [roadrunnerlenny/etlbox#72]
**Describe the bug**
The dest.Wait() throws a ORA-00904: "COL": invalid identifier .When using OracleConnectionManager

**Steps To Reproduce**
 _Create A Table In oracle , With just one column(Id) for demonstration purpose_

 `OracleConnectionManager orcon = new OracleConnectionManager("oracle connectionstring"));`
 `ControlFlow.DefaultDbConnection = orcon;`
 ` CsvSource<MyData>  source = new CsvSource<MyData>("demo.csv");`
  _Take a sample record from the CSV Should have Id_
 ```
DbDestination<MyData> dest= new DbDestination<MyData>(orcon, "Table");
 source.LinkTo(dest);             
 source.Execute();
 destOralce.Wait();
```

**Actual behaviour**
  ORA-00904: "COL": invalid identifier Error , 
Wherease if we use SqlConnectionManager & sqlserver as the database the records are getting inserted . Its Successful , But not with oralce 

**Expected behavior**

Since It works well for SqlServer , So should have worked nice with Oracle But it Didn't :disappointed: :disappointed: :disappointed: :sob: :sob: :sob: :sob: :sob:

**Comment by roadrunnerlenny** [comment]
Hi @BabuBahir ,

thanks for using ETLBox and your feedback.

I guess the error is related to some oracle database specifics (perhaps some implicit naming conventions or data type issue)  - I would like to reproduce the error in my local test environment.
Could you give me some more details about your setup: 
The CREATE TABLE statement for your test table, and the header row & one example row for your csv data? As well as the data type you used in your MyData object?

Generally, there are a lot of test cases for many scenario in the test project (>500 test cases), you to reassure you that the connection managers was tested before...

**Comment by BabuBahir** [comment]
Thank for the reply  @roadrunnerlenny  .
What i will do is create a small dotnetcore project . Running which You shall be able to reproduce the error . I will provide the link to the github repo here. .

**Comment by roadrunnerlenny** [comment]
Hi @BabuBahir ,
that sounds good, just post the link here and I will look into it.

**Comment by BabuBahir** [comment]
Hi @roadrunnerlenny  . Here is the [github link ](https://github.com/BabuBahir/etlbox)which shall reproduce the error... Have made a webapp .


Now , I initially thought that there might be some issue in the CreateTableTask for oracle that was stopping the insertion of data but it isn't . Because when i tried creating a table first in the oracle 11g database. and then directly did the source.Execute(); the error was still the same.

So i guess the issue is with oracle 11g & the libraries

**Comment by roadrunnerlenny** [comment]
Hi @BabuBahir ,

I just had a look at your project. In general, the code looks good and should work without errors. 

Anyways, I had some issue with the versions and references to get it up and running. I must admit that since version 2.0.0 and the split up in separate packages, I did have some problems with the package creation and how to keep up the references working. 

So here what I did to make this work on my environment: 
I downgraded the .NET version to 2.1 (and also the corresponding ASP.NET packages to 2.1), because 2.2 is not supported any more. 
For some reason, I got an error that the package reference was not set to the correct ETLBox version when clicking on the Oracle link (by the way, thanks for the big font, made it easy to find ;) )
So I upgraded the connection managers (all of them) to the latest 1.0.2 and ETLBox to the latest 2.0.3.

This worked like charm on my machine. Data was inserted without issues. 

I created a PR for your demo project that basically reflects these changes. 

But I guess that this not what was is causing the issue.

My local oracle database is version 12c (Enterprise). 
I am using the offical Oracle .NET Core  connector - this is supposed only to work with Oracle 12c. 
There is currently no official Oracle .NET Core connector for version 11... 
Can you upgrade your database to 12c? 

If you know other connectors for Oracle that support ADO .NET core , let me know. I probably could try out if they work together with ETLBox. 
Right now, I am only aware of this one: https://www.devart.com/dotconnect/oracle/

**Comment by roadrunnerlenny** [comment]
Hi @BabuBahir ,

just another possible workaround which could work with Oracle 11. 
Instead of using the "native" connector you could try to connect using an Odbc connection.

I just uploaded a new version (1.0.3) of the ETLBox.Odbc package which contains an OracleOdbcConnectionManager. 
Use this connection manager instead of the OracleConnectionManager and reference the latest package (https://www.nuget.org/packages/ETLBox.Odbc/1.0.3)

The prerequisite to make this work is that you have the Odbc driver installed and set up on your system. The official docu for installing an odbc driver from oracle can be found here: https://www.oracle.com/database/technologies/releasenote-odbc-ic.html

The connection string would look different, something like this 
`Driver={Oracle in OracleInstallationFolder};DBQ=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.211.55.2)(PORT=1521)))(CONNECT_DATA=(SID=ORCLCDB)));UID=username;PWD=password;"`

OracleInstallationFolder was in my case where I "installed" the Odbc driver. 

This work in my environment - i could succesfully connect to an Oracle database via Odbc.

**Comment by BabuBahir** [comment]
Thanks for the reply @roadrunnerlenny .... I shall try it again when I have access to my system this monday.

Anyways I would like to thank you for creating such a simplistic ETL on dotnet core. 
Had I not found [etlbox](https://github.com/roadrunnerlenny/etlbox) I would have to go for Talend .

**Comment by roadrunnerlenny** [comment]
Hi @BabuBahir,

were you able to solve your issue? Any feedback is appreciated.
