### ISSUE TITLE
Skip and/or Ignore Lines in flat/csv files

### ISSUE THREAD

**Issue by smmarrocco** [roadrunnerlenny/etlbox#8]
Great project! looking into using it for one of our ETL pipelines. After going through the documentation and examples, I'm not entirely clear on how I can skip/ignore lines? Would this be done via RowTransformation?

For a bit of an example, some of the source files received will include a tail or footer. Along with some not containing headers or containing headers and others with headers that consist of two rows.

**Comment by roadrunnerlenny** [comment]
Hey,

thanks for you comment! You closed the issue right after raising it, did that mean you could already solve your issue or did this happen accidentally?

Just in case you are still having problems to skip rows in the source files, here are three examples that could help you.

1. I just added (again) the Property `SkipRows` to the `CSVSource`. The default value here is 0. If you set a value greater than 0, e.g. 2, the CSVSource will skip the first 2 rows of the source file before actually reading the data. 
Here is some example code how to use this property:
https://github.com/roadrunnerlenny/etlbox/blob/83bd9b57c6a962948711f184ddb702a3417d6917/ETLBoxTest/src/DataFlow/TestDataFlowCSVSource.cs#L167-L184

2. The above property only works for the first lines of a soure file. If you have some lines within your CSV file, you can use the CSVHelper configuration to set a comment character. Every line that starts with this character will be ignored.
```C#
CSVSource<CSVData> source = new CSVSource<CSVData>("src/DataFlow/CSVSkipRows.csv");
source.Configuration.Comment = '/'; //# is actually the default
```

3. Another way to deal with data which you want to sort out is to use Predicates. Predicates can be used every time you link data flow components together. 

E.g.
```C#
source.LinkTo(dest1, input => input[0] != "Test");
source.LinkTo(dest2, input => input[0] == "Test");
```
But you have to make sure that all rows are processed by a destination, otherwise the dataflow will never finish. If you want to discard rows, the easiest way would be to define a `CustomDestination` that ignores the data (alternatively you could log some information here).

Here is an example code to identify duplicates and the use of Predicates to filter them out. It also shows the use of the `CustomDestination` to ignore the duplicate data.

https://github.com/roadrunnerlenny/etlbox/blob/83bd9b57c6a962948711f184ddb702a3417d6917/ETLBoxTest/src/DataFlowExamples/TestIssue5_DuplicateCheck.cs#L42-L84
